apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "myapp-role"
    vault.hashicorp.com/agent-inject-secret-config.txt: "secret/data/myapp"
spec:
  serviceAccountName: myapp-sa
  containers:
    - name: myapp
      image: nginx
      volumeMounts:
        - name: vault-secret
          mountPath: "/mnt/vault/secrets"
  volumes:
    - name: vault-secret
      emptyDir: {}
